[project]
name = "doh1-autofill"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.2.0",
    "platformdirs>=4.3.8",
    "pydantic>=2.11.5",
    "selenium>=4.33.0",
]
